// Generated by pnpm characters:assets. Do not edit by hand.
import type { ImageSourcePropType } from "react-native";

export const characterAvatarSources: Partial<Record<string, ImageSourcePropType>> = {};
export const characterFeedSources: Partial<Record<string, ImageSourcePropType>> = {};
