/* eslint-disable @typescript-eslint/no-require-imports -- Metro requires static local asset references. */
import type { SportType } from "@moveall/contracts";
import type { ImageSourcePropType } from "react-native";

/** Design archive only. These sample records are not award definitions or user achievements. */
export type NeonMedalDesign = {
  id: string;
  sport: SportType;
  name: string;
  title: string;
  metric: string;
};
export const neonMedalSports: { key: SportType; label: string }[] = [
  { key: "running", label: "러닝" },
  { key: "hiking", label: "등산" },
  { key: "cycling", label: "사이클" },
  { key: "strength", label: "근력" },
  { key: "swimming", label: "수영" },
  { key: "diving", label: "다이빙" },
];
export const neonMedalDesigns: NeonMedalDesign[] = [
  {
    id: "R01",
    sport: "running",
    name: "LANE BIB",
    title: "레인 빕",
    metric: "21.1 km",
  },
  {
    id: "R02",
    sport: "running",
    name: "SPEED SOLE",
    title: "스피드 솔",
    metric: "10 km",
  },
  {
    id: "R03",
    sport: "running",
    name: "FINISH BREAK",
    title: "피니시 브레이크",
    metric: "5 km",
  },
  {
    id: "R04",
    sport: "running",
    name: "STRIDE MARK",
    title: "스트라이드 마크",
    metric: "5K",
  },
  {
    id: "R05",
    sport: "running",
    name: "SPLIT TIMER",
    title: "스플릿 타이머",
    metric: "27:50",
  },
  {
    id: "R06",
    sport: "running",
    name: "START GATE",
    title: "스타트 게이트",
    metric: "10 km",
  },
  {
    id: "R07",
    sport: "running",
    name: "LACE LOCK",
    title: "레이스 락",
    metric: "5.24 km",
  },
  {
    id: "R08",
    sport: "running",
    name: "DOUBLE STEP",
    title: "더블 스텝",
    metric: "42.2 km",
  },
  {
    id: "R09",
    sport: "running",
    name: "TRACK BEND",
    title: "트랙 벤드",
    metric: "400 m",
  },
  {
    id: "R10",
    sport: "running",
    name: "HEEL SPRING",
    title: "힐 스프링",
    metric: "20 km",
  },
  {
    id: "H01",
    sport: "hiking",
    name: "PEAK CARABINER",
    title: "피크 카라비너",
    metric: "500 m",
  },
  {
    id: "H02",
    sport: "hiking",
    name: "CONTOUR RISE",
    title: "컨투어 라이즈",
    metric: "1000 m",
  },
  {
    id: "H03",
    sport: "hiking",
    name: "RIDGE SPINE",
    title: "리지 스파인",
    metric: "884 m",
  },
  {
    id: "H04",
    sport: "hiking",
    name: "SUMMIT TREAD",
    title: "서밋 트레드",
    metric: "10 km",
  },
  {
    id: "H05",
    sport: "hiking",
    name: "NORTH PEAK",
    title: "노스 피크",
    metric: "1500 m",
  },
  {
    id: "H06",
    sport: "hiking",
    name: "TRAIL POST",
    title: "트레일 포스트",
    metric: "12 km",
  },
  {
    id: "H07",
    sport: "hiking",
    name: "POLE ASCENT",
    title: "폴 어센트",
    metric: "700 m",
  },
  {
    id: "H08",
    sport: "hiking",
    name: "SWITCHBACK",
    title: "스위치백",
    metric: "800 m",
  },
  {
    id: "H09",
    sport: "hiking",
    name: "VALLEY WINDOW",
    title: "밸리 윈도",
    metric: "1200 m",
  },
  {
    id: "H10",
    sport: "hiking",
    name: "SUMMIT FLAG",
    title: "서밋 플래그",
    metric: "2000 m",
  },
  {
    id: "C01",
    sport: "cycling",
    name: "CRANK EVOLVE",
    title: "크랭크 이볼브",
    metric: "100 km",
  },
  {
    id: "C02",
    sport: "cycling",
    name: "CHAIN LINK",
    title: "체인 링크",
    metric: "50 km",
  },
  {
    id: "C03",
    sport: "cycling",
    name: "TWIN RIM",
    title: "트윈 림",
    metric: "200 km",
  },
  {
    id: "C04",
    sport: "cycling",
    name: "CRANK ARM",
    title: "크랭크 암",
    metric: "75 km",
  },
  {
    id: "C05",
    sport: "cycling",
    name: "DROP BAR",
    title: "드롭 바",
    metric: "120 km",
  },
  {
    id: "C06",
    sport: "cycling",
    name: "PEDAL CAGE",
    title: "페달 케이지",
    metric: "30 km",
  },
  {
    id: "C07",
    sport: "cycling",
    name: "VELO BANK",
    title: "벨로 뱅크",
    metric: "250 km",
  },
  {
    id: "C08",
    sport: "cycling",
    name: "AERO HELMET",
    title: "에어로 헬멧",
    metric: "60 km",
  },
  {
    id: "C09",
    sport: "cycling",
    name: "SPOKE FAN",
    title: "스포크 팬",
    metric: "150 km",
  },
  {
    id: "C10",
    sport: "cycling",
    name: "FRAME LOCK",
    title: "프레임 락",
    metric: "300 km",
  },
  {
    id: "S01",
    sport: "strength",
    name: "PLATE CUT",
    title: "플레이트 컷",
    metric: "20 kg",
  },
  {
    id: "S02",
    sport: "strength",
    name: "BAR BRIDGE",
    title: "바 브리지",
    metric: "50 SESSIONS",
  },
  {
    id: "S03",
    sport: "strength",
    name: "KETTLE CORE",
    title: "케틀 코어",
    metric: "16 kg",
  },
  {
    id: "S04",
    sport: "strength",
    name: "RACK PORTAL",
    title: "랙 포털",
    metric: "100 SESSIONS",
  },
  {
    id: "S05",
    sport: "strength",
    name: "HEX PAIR",
    title: "헥스 페어",
    metric: "25 kg",
  },
  {
    id: "S06",
    sport: "strength",
    name: "COLLAR LOCK",
    title: "칼라 락",
    metric: "10 SESSIONS",
  },
  {
    id: "S07",
    sport: "strength",
    name: "GRIP FORCE",
    title: "그립 포스",
    metric: "50 kg",
  },
  {
    id: "S08",
    sport: "strength",
    name: "CABLE PULL",
    title: "케이블 풀",
    metric: "75 SESSIONS",
  },
  {
    id: "S09",
    sport: "strength",
    name: "LOAD STACK",
    title: "로드 스택",
    metric: "100 kg",
  },
  {
    id: "S10",
    sport: "strength",
    name: "POWER ARC",
    title: "파워 아크",
    metric: "30 SESSIONS",
  },
  {
    id: "W01",
    sport: "swimming",
    name: "POOL LANES",
    title: "풀 레인",
    metric: "1500 m",
  },
  {
    id: "W02",
    sport: "swimming",
    name: "GOGGLE LINK",
    title: "고글 링크",
    metric: "1000 m",
  },
  {
    id: "W03",
    sport: "swimming",
    name: "TURN WALL",
    title: "턴 월",
    metric: "50 m",
  },
  {
    id: "W04",
    sport: "swimming",
    name: "STROKE CREST",
    title: "스트로크 크레스트",
    metric: "2000 m",
  },
  {
    id: "W05",
    sport: "swimming",
    name: "LANE BUOY",
    title: "레인 부이",
    metric: "800 m",
  },
  {
    id: "W06",
    sport: "swimming",
    name: "START BLOCK",
    title: "스타트 블록",
    metric: "400 m",
  },
  {
    id: "W07",
    sport: "swimming",
    name: "PADDLE FLOW",
    title: "패들 플로우",
    metric: "1200 m",
  },
  {
    id: "W08",
    sport: "swimming",
    name: "STREAMLINE",
    title: "스트림라인",
    metric: "2500 m",
  },
  {
    id: "W09",
    sport: "swimming",
    name: "WAVE TILE",
    title: "웨이브 타일",
    metric: "500 m",
  },
  {
    id: "W10",
    sport: "swimming",
    name: "KICK FLOW",
    title: "킥 플로우",
    metric: "1800 m",
  },
  {
    id: "D01",
    sport: "diving",
    name: "MASK DEPTH",
    title: "마스크 뎁스",
    metric: "20 m",
  },
  {
    id: "D02",
    sport: "diving",
    name: "LONGFIN",
    title: "롱핀",
    metric: "30 m",
  },
  {
    id: "D03",
    sport: "diving",
    name: "DESCENT LINE",
    title: "디센트 라인",
    metric: "15 m",
  },
  {
    id: "D04",
    sport: "diving",
    name: "FREEFALL",
    title: "프리폴",
    metric: "25 m",
  },
  {
    id: "D05",
    sport: "diving",
    name: "SURFACE BUOY",
    title: "서피스 부이",
    metric: "10 m",
  },
  {
    id: "D06",
    sport: "diving",
    name: "DEPTH DISC",
    title: "뎁스 디스크",
    metric: "30 m",
  },
  {
    id: "D07",
    sport: "diving",
    name: "CANYON DIVE",
    title: "캐니언 다이브",
    metric: "20 m",
  },
  {
    id: "D08",
    sport: "diving",
    name: "MONOFIN",
    title: "모노핀",
    metric: "15 m",
  },
  {
    id: "D09",
    sport: "diving",
    name: "BUBBLE PATH",
    title: "버블 패스",
    metric: "10 m",
  },
  {
    id: "D10",
    sport: "diving",
    name: "ABYSS PORTAL",
    title: "어비스 포털",
    metric: "25 m",
  },
];
export const neonMedalSources: Record<string, ImageSourcePropType> = {
  R01: require("../../assets/images/medal-neon-60/r01.webp"),
  R02: require("../../assets/images/medal-neon-60/r02.webp"),
  R03: require("../../assets/images/medal-neon-60/r03.webp"),
  R04: require("../../assets/images/medal-neon-60/r04.webp"),
  R05: require("../../assets/images/medal-neon-60/r05.webp"),
  R06: require("../../assets/images/medal-neon-60/r06.webp"),
  R07: require("../../assets/images/medal-neon-60/r07.webp"),
  R08: require("../../assets/images/medal-neon-60/r08.webp"),
  R09: require("../../assets/images/medal-neon-60/r09.webp"),
  R10: require("../../assets/images/medal-neon-60/r10.webp"),
  H01: require("../../assets/images/medal-neon-60/h01.webp"),
  H02: require("../../assets/images/medal-neon-60/h02.webp"),
  H03: require("../../assets/images/medal-neon-60/h03.webp"),
  H04: require("../../assets/images/medal-neon-60/h04.webp"),
  H05: require("../../assets/images/medal-neon-60/h05.webp"),
  H06: require("../../assets/images/medal-neon-60/h06.webp"),
  H07: require("../../assets/images/medal-neon-60/h07.webp"),
  H08: require("../../assets/images/medal-neon-60/h08.webp"),
  H09: require("../../assets/images/medal-neon-60/h09.webp"),
  H10: require("../../assets/images/medal-neon-60/h10.webp"),
  C01: require("../../assets/images/medal-neon-60/c01.webp"),
  C02: require("../../assets/images/medal-neon-60/c02.webp"),
  C03: require("../../assets/images/medal-neon-60/c03.webp"),
  C04: require("../../assets/images/medal-neon-60/c04.webp"),
  C05: require("../../assets/images/medal-neon-60/c05.webp"),
  C06: require("../../assets/images/medal-neon-60/c06.webp"),
  C07: require("../../assets/images/medal-neon-60/c07.webp"),
  C08: require("../../assets/images/medal-neon-60/c08.webp"),
  C09: require("../../assets/images/medal-neon-60/c09.webp"),
  C10: require("../../assets/images/medal-neon-60/c10.webp"),
  S01: require("../../assets/images/medal-neon-60/s01.webp"),
  S02: require("../../assets/images/medal-neon-60/s02.webp"),
  S03: require("../../assets/images/medal-neon-60/s03.webp"),
  S04: require("../../assets/images/medal-neon-60/s04.webp"),
  S05: require("../../assets/images/medal-neon-60/s05.webp"),
  S06: require("../../assets/images/medal-neon-60/s06.webp"),
  S07: require("../../assets/images/medal-neon-60/s07.webp"),
  S08: require("../../assets/images/medal-neon-60/s08.webp"),
  S09: require("../../assets/images/medal-neon-60/s09.webp"),
  S10: require("../../assets/images/medal-neon-60/s10.webp"),
  W01: require("../../assets/images/medal-neon-60/w01.webp"),
  W02: require("../../assets/images/medal-neon-60/w02.webp"),
  W03: require("../../assets/images/medal-neon-60/w03.webp"),
  W04: require("../../assets/images/medal-neon-60/w04.webp"),
  W05: require("../../assets/images/medal-neon-60/w05.webp"),
  W06: require("../../assets/images/medal-neon-60/w06.webp"),
  W07: require("../../assets/images/medal-neon-60/w07.webp"),
  W08: require("../../assets/images/medal-neon-60/w08.webp"),
  W09: require("../../assets/images/medal-neon-60/w09.webp"),
  W10: require("../../assets/images/medal-neon-60/w10.webp"),
  D01: require("../../assets/images/medal-neon-60/d01.webp"),
  D02: require("../../assets/images/medal-neon-60/d02.webp"),
  D03: require("../../assets/images/medal-neon-60/d03.webp"),
  D04: require("../../assets/images/medal-neon-60/d04.webp"),
  D05: require("../../assets/images/medal-neon-60/d05.webp"),
  D06: require("../../assets/images/medal-neon-60/d06.webp"),
  D07: require("../../assets/images/medal-neon-60/d07.webp"),
  D08: require("../../assets/images/medal-neon-60/d08.webp"),
  D09: require("../../assets/images/medal-neon-60/d09.webp"),
  D10: require("../../assets/images/medal-neon-60/d10.webp"),
};
